// ES module version of componentsDB
export const componentsDB = {
  cpu: [
    { id: 1, name: 'AMD Ryzen 9 7950X', brand: 'AMD', vendors: [{ name: 'PrimeABGB', price: 47990, url: 'https://primeabgb.com', stock: true }] },
    { id: 2, name: 'AMD Ryzen 7 7800X3D', brand: 'AMD', vendors: [ { name: 'Amazon', price: 34990, url: 'https://amazon.in', stock: true }, { name: 'Computech', price: 35500, url: 'https://computech.in', stock: false } ] },
    { id: 25, name: 'AMD Ryzen 5 7600X', brand: 'AMD', vendors: [ { name: 'Vedant', price: 21500, url: 'https://vedantcomputers.com', stock: true } ] },
    { id: 3, name: 'Intel Core i9-13900K', brand: 'Intel', vendors: [ { name: 'MDComputers', price: 52999, url: 'https://mdcomputers.in', stock: false } ] },
    { id: 4, name: 'Intel Core i7-13700K', brand: 'Intel', vendors: [ { name: 'Amazon', price: 38999, url: 'https://amazon.in', stock: true }, { name: 'PrimeABGB', price: 39500, url: 'https://primeabgb.com', stock: true } ] },
    { id: 26, name: 'Intel Core i5-13600K', brand: 'Intel', vendors: [ { name: 'Amazon', price: 29990, url: 'https://amazon.in', stock: false } ] },
    { id: 101, name: 'AMD Ryzen 9 7900X', brand: 'AMD', vendors: [ { name: 'Amazon', price: 37990, url: 'https://amazon.in', stock: true }, { name: 'MDComputers', price: 38500, url: 'https://mdcomputers.in', stock: true } ] },
    { id: 102, name: 'AMD Ryzen 7 7700X', brand: 'AMD', vendors: [ { name: 'Vedant', price: 28990, url: 'https://vedantcomputers.com', stock: true } ] },
    { id: 103, name: 'AMD Ryzen 5 7600', brand: 'AMD', vendors: [ { name: 'Computech', price: 19990, url: 'https://computech.in', stock: true } ] },
    { id: 104, name: 'AMD Ryzen 5 5600X', brand: 'AMD', vendors: [ { name: 'Amazon', price: 14990, url: 'https://amazon.in', stock: true } ] },
    { id: 105, name: 'Intel Core i9-14900K', brand: 'Intel', vendors: [ { name: 'PrimeABGB', price: 56999, url: 'https://primeabgb.com', stock: true }, { name: 'MDComputers', price: 55999, url: 'https://mdcomputers.in', stock: false } ] },
    { id: 106, name: 'Intel Core i7-14700K', brand: 'Intel', vendors: [ { name: 'Amazon', price: 43999, url: 'https://amazon.in', stock: true } ] },
    { id: 107, name: 'Intel Core i5-14600K', brand: 'Intel', vendors: [ { name: 'Vedant', price: 31990, url: 'https://vedantcomputers.com', stock: true } ] },
    { id: 108, name: 'Intel Core i5-12400F', brand: 'Intel', vendors: [ { name: 'Computech', price: 12990, url: 'https://computech.in', stock: true } ] },
    { id: 109, name: 'Intel Core i3-12100F', brand: 'Intel', vendors: [ { name: 'Amazon', price: 7990, url: 'https://amazon.in', stock: true } ] }
  ],
  motherboard: [
    { id: 5, name: 'ASUS ROG Crosshair X670E Hero', brand: 'AMD', ramType: 'DDR5', formFactor: 'ATX', vendors: [ { name: 'Computech', price: 65000, url: 'https://computech.in', stock: true } ] },
    { id: 3, name: 'Gigabyte B650 AORUS Elite', brand: 'AMD', ramType: 'DDR5', formFactor: 'ATX', vendors: [ { name: 'Vedant', price: 21500, url: 'https://vedantcomputers.com', stock: true } ] },
    { id: 27, name: 'ASRock B650M PG Riptide', brand: 'AMD', ramType: 'DDR5', formFactor: 'Micro-ATX', vendors: [ { name: 'MDComputers', price: 18990, url: 'https://mdcomputers.in', stock: true } ] },
    { id: 4, name: 'MSI MAG Z790 Tomahawk', brand: 'Intel', ramType: 'DDR5', formFactor: 'ATX', vendors: [ { name: 'Computech', price: 28999, url: 'https://computech.in', stock: false } ] },
    { id: 8, name: 'ASRock Z790M-ITX WIFI', brand: 'Intel', ramType: 'DDR5', formFactor: 'Mini-ITX', vendors: [ { name: 'PrimeABGB', price: 24500, url: 'https://primeabgb.com', stock: true } ] },
    { id: 28, name: 'Gigabyte Z790 AORUS Master', brand: 'Intel', ramType: 'DDR5', formFactor: 'E-ATX', vendors: [ { name: 'Computech', price: 54999, url: 'https://computech.in', stock: true } ] },
    { id: 201, name: 'ASUS TUF Gaming B650-PLUS', brand: 'AMD', ramType: 'DDR5', formFactor: 'ATX', vendors: [ { name: 'Amazon', price: 21990, url: 'https://amazon.in', stock: true } ] },
    { id: 202, name: 'MSI PRO B650M-A WIFI', brand: 'AMD', ramType: 'DDR5', formFactor: 'Micro-ATX', vendors: [ { name: 'MDComputers', price: 18990, url: 'https://mdcomputers.in', stock: true } ] },
    { id: 203, name: 'Gigabyte X670 AORUS Elite AX', brand: 'AMD', ramType: 'DDR5', formFactor: 'ATX', vendors: [ { name: 'Vedant', price: 32990, url: 'https://vedantcomputers.com', stock: true } ] },
    { id: 204, name: 'ASUS ROG Strix Z790-E Gaming WIFI', brand: 'Intel', ramType: 'DDR5', formFactor: 'ATX', vendors: [ { name: 'PrimeABGB', price: 48999, url: 'https://primeabgb.com', stock: true } ] },
    { id: 205, name: 'MSI MAG B760 Tomahawk WIFI', brand: 'Intel', ramType: 'DDR5', formFactor: 'ATX', vendors: [ { name: 'Computech', price: 22999, url: 'https://computech.in', stock: true } ] },
    { id: 206, name: 'ASRock B760M Pro RS', brand: 'Intel', ramType: 'DDR5', formFactor: 'Micro-ATX', vendors: [ { name: 'Amazon', price: 15990, url: 'https://amazon.in', stock: true } ] },
    { id: 207, name: 'Gigabyte B660M DS3H AX DDR4', brand: 'Intel', ramType: 'DDR4', formFactor: 'Micro-ATX', vendors: [ { name: 'MDComputers', price: 12990, url: 'https://mdcomputers.in', stock: true } ] },
    { id: 208, name: 'ASUS Prime B660-PLUS D4', brand: 'Intel', ramType: 'DDR4', formFactor: 'ATX', vendors: [ { name: 'Vedant', price: 13990, url: 'https://vedantcomputers.com', stock: true } ] }
  ],
  ram: [
    { id: 9, name: 'G.Skill Trident Z5 Neo 32GB DDR5', ramType: 'DDR5', vendors: [ { name: 'Computech', price: 11499, url: 'https://computech.in', stock: true } ] },
    { id: 10, name: 'Corsair Vengeance 32GB DDR5', ramType: 'DDR5', vendors: [ { name: 'Amazon', price: 9999, url: 'https://amazon.in', stock: true }, { name: 'Vedant', price: 10200, url: 'https://vedantcomputers.com', stock: false } ] },
    { id: 11, name: 'Corsair Vengeance LPX 16GB DDR4', ramType: 'DDR4', vendors: [ { name: 'MDComputers', price: 3800, url: 'https://mdcomputers.in', stock: true } ] },
    { id: 301, name: 'Kingston Fury Beast 32GB DDR5', ramType: 'DDR5', vendors: [ { name: 'Amazon', price: 9990, url: 'https://amazon.in', stock: true } ] },
    { id: 302, name: 'Corsair Dominator Platinum RGB 32GB DDR5', ramType: 'DDR5', vendors: [ { name: 'PrimeABGB', price: 14990, url: 'https://primeabgb.com', stock: true } ] },
    { id: 303, name: 'G.Skill Ripjaws V 16GB DDR4', ramType: 'DDR4', vendors: [ { name: 'Vedant', price: 3290, url: 'https://vedantcomputers.com', stock: true } ] },
    { id: 304, name: 'TEAMGROUP T-Force Vulcan Z 32GB DDR4', ramType: 'DDR4', vendors: [ { name: 'Amazon', price: 5890, url: 'https://amazon.in', stock: true } ] },
    { id: 305, name: 'Kingston Fury Beast 16GB DDR5', ramType: 'DDR5', vendors: [ { name: 'Computech', price: 5490, url: 'https://computech.in', stock: true } ] },
    { id: 306, name: 'Crucial Pro 32GB DDR5', ramType: 'DDR5', vendors: [ { name: 'Amazon', price: 10490, url: 'https://amazon.in', stock: true } ] }
  ],
  gpu: [
    { id: 12, name: 'NVIDIA GeForce RTX 4090 24GB', vendors: [ { name: 'PrimeABGB', price: 175000, url: 'https://primeabgb.com', stock: false } ] },
    { id: 31, name: 'NVIDIA GeForce RTX 4080 16GB', vendors: [ { name: 'Computech', price: 125000, url: 'https://computech.in', stock: true } ] },
    { id: 13, name: 'NVIDIA GeForce RTX 4070 Ti 12GB', vendors: [ { name: 'Vedant', price: 85000, url: 'https://vedantcomputers.com', stock: true }, { name: 'MDComputers', price: 86500, url: 'https://mdcomputers.in', stock: true } ] },
    { id: 401, name: 'NVIDIA GeForce RTX 4060 8GB', vendors: [ { name: 'Amazon', price: 28990, url: 'https://amazon.in', stock: true } ] },
    { id: 402, name: 'NVIDIA GeForce RTX 4070 12GB', vendors: [ { name: 'PrimeABGB', price: 50990, url: 'https://primeabgb.com', stock: true } ] },
    { id: 403, name: 'NVIDIA GeForce RTX 4070 SUPER 12GB', vendors: [ { name: 'MDComputers', price: 55990, url: 'https://mdcomputers.in', stock: true } ] },
    { id: 404, name: 'NVIDIA GeForce RTX 4080 SUPER 16GB', vendors: [ { name: 'Computech', price: 114990, url: 'https://computech.in', stock: true } ] },
    { id: 405, name: 'AMD Radeon RX 7900 XTX 24GB', vendors: [ { name: 'Vedant', price: 99990, url: 'https://vedantcomputers.com', stock: true } ] },
    { id: 406, name: 'AMD Radeon RX 7900 XT 20GB', vendors: [ { name: 'Amazon', price: 89990, url: 'https://amazon.in', stock: true } ] },
    { id: 407, name: 'AMD Radeon RX 7800 XT 16GB', vendors: [ { name: 'PrimeABGB', price: 52990, url: 'https://primeabgb.com', stock: true } ] },
    { id: 408, name: 'AMD Radeon RX 7700 XT 12GB', vendors: [ { name: 'MDComputers', price: 43990, url: 'https://mdcomputers.in', stock: true } ] }
  ],
  storage: [
    { id: 15, name: 'Samsung 990 Pro 2TB NVMe SSD', vendors: [ { name: 'Amazon', price: 14999, url: 'https://amazon.in', stock: true } ] },
    { id: 16, name: 'Crucial P5 Plus 2TB NVMe SSD', vendors: [ { name: 'Computech', price: 11990, url: 'https://computech.in', stock: false } ] },
    { id: 33, name: 'WD Black SN850X 1TB NVMe SSD', vendors: [ { name: 'Amazon', price: 8500, url: 'https://amazon.in', stock: true } ] },
    { id: 34, name: 'Samsung 870 EVO 1TB SATA SSD', vendors: [ { name: 'Computech', price: 7500, url: 'https://computech.in', stock: true } ] },
    { id: 35, name: 'Seagate Barracuda 4TB HDD', vendors: [ { name: 'Amazon', price: 7990, url: 'https://amazon.in', stock: true } ] },
    { id: 501, name: 'Kingston KC3000 1TB NVMe SSD', vendors: [ { name: 'Amazon', price: 7490, url: 'https://amazon.in', stock: true } ] },
    { id: 502, name: 'WD Blue SN570 1TB NVMe SSD', vendors: [ { name: 'Vedant', price: 5590, url: 'https://vedantcomputers.com', stock: true } ] },
    { id: 503, name: 'Crucial T700 2TB NVMe SSD', vendors: [ { name: 'PrimeABGB', price: 26500, url: 'https://primeabgb.com', stock: true } ] },
    { id: 504, name: 'Samsung 980 1TB NVMe SSD', vendors: [ { name: 'Computech', price: 6390, url: 'https://computech.in', stock: true } ] },
    { id: 505, name: 'Seagate FireCuda 530 1TB NVMe SSD', vendors: [ { name: 'MDComputers', price: 12990, url: 'https://mdcomputers.in', stock: true } ] },
    { id: 506, name: 'WD Black SN770 2TB NVMe SSD', vendors: [ { name: 'Amazon', price: 14290, url: 'https://amazon.in', stock: true } ] },
    { id: 507, name: 'Crucial MX500 1TB SATA SSD', vendors: [ { name: 'Vedant', price: 6490, url: 'https://vedantcomputers.com', stock: true } ] },
    { id: 508, name: 'Seagate Barracuda 2TB HDD', vendors: [ { name: 'Amazon', price: 4990, url: 'https://amazon.in', stock: true } ] }
  ],
  psu: [
    { id: 18, name: 'Corsair RM1000e 1000W Gold', vendors: [ { name: 'Amazon', price: 15500, url: 'https://amazon.in', stock: true } ] },
    { id: 19, name: 'SeaSonic FOCUS Plus 850W Gold', vendors: [ { name: 'Computech', price: 13500, url: 'https://computech.in', stock: true } ] },
    { id: 36, name: 'Cooler Master MWE 750W Bronze', vendors: [ { name: 'Amazon', price: 6500, url: 'https://amazon.in', stock: true } ] },
    { id: 601, name: 'Corsair RM850x 850W Gold', vendors: [ { name: 'PrimeABGB', price: 12990, url: 'https://primeabgb.com', stock: true } ] },
    { id: 602, name: 'Seasonic PRIME TX-1000 1000W Titanium', vendors: [ { name: 'MDComputers', price: 28990, url: 'https://mdcomputers.in', stock: true } ] },
    { id: 603, name: 'Cooler Master V850 Gold', vendors: [ { name: 'Computech', price: 11990, url: 'https://computech.in', stock: true } ] },
    { id: 604, name: 'MSI MPG A850G PCIE5 850W', vendors: [ { name: 'Amazon', price: 13990, url: 'https://amazon.in', stock: true } ] },
    { id: 605, name: 'Antec EarthWatts Gold Pro 750W', vendors: [ { name: 'Vedant', price: 8990, url: 'https://vedantcomputers.com', stock: true } ] },
    { id: 606, name: 'DeepCool PQ1000G 1000W Gold', vendors: [ { name: 'PrimeABGB', price: 15490, url: 'https://primeabgb.com', stock: true } ] }
  ],
  pcCase: [
    { id: 20, name: 'Lian Li Lancool 216', formFactor: 'ATX', vendors: [ { name: 'Computech', price: 8500, url: 'https://computech.in', stock: false } ] },
    { id: 37, name: 'Fractal Design North', formFactor: 'ATX', vendors: [ { name: 'Computech', price: 13990, url: 'https://computech.in', stock: true } ] },
    { id: 22, name: 'Cooler Master NR200P', formFactor: 'Mini-ITX', vendors: [ { name: 'Amazon', price: 9200, url: 'https://amazon.in', stock: true } ] },
    { id: 701, name: 'NZXT H5 Flow', formFactor: 'ATX', vendors: [ { name: 'Amazon', price: 10990, url: 'https://amazon.in', stock: true } ] },
    { id: 702, name: 'Fractal Design Meshify 2', formFactor: 'ATX', vendors: [ { name: 'Vedant', price: 17990, url: 'https://vedantcomputers.com', stock: true } ] },
    { id: 703, name: 'Lian Li O11 Dynamic', formFactor: 'ATX', vendors: [ { name: 'PrimeABGB', price: 15990, url: 'https://primeabgb.com', stock: true } ] },
    { id: 704, name: 'Cooler Master NR400', formFactor: 'Micro-ATX', vendors: [ { name: 'MDComputers', price: 5990, url: 'https://mdcomputers.in', stock: true } ] },
    { id: 705, name: 'NZXT H1 V2', formFactor: 'Mini-ITX', vendors: [ { name: 'Computech', price: 25990, url: 'https://computech.in', stock: true } ] },
    { id: 706, name: 'Phanteks Eclipse G360A', formFactor: 'ATX', vendors: [ { name: 'Amazon', price: 8990, url: 'https://amazon.in', stock: true } ] }
  ],
  monitor: [
    { id: 23, name: 'Dell Alienware AW3423DWF 34" QD-OLED', vendors: [ { name: 'Dell', price: 95000, url: 'https://dell.com', stock: true } ] },
    { id: 24, name: 'LG UltraGear 27GR95QE-B 27" OLED', vendors: [ { name: 'Best Buy', price: 89990, url: 'https://bestbuy.com', stock: false } ] },
    { id: 38, name: 'Gigabyte M27Q 27" IPS 170Hz', vendors: [ { name: 'Amazon', price: 29500, url: 'https://amazon.in', stock: true } ] },
    { id: 801, name: 'LG 27GP850 27" 1440p 165Hz', vendors: [ { name: 'Amazon', price: 27990, url: 'https://amazon.in', stock: true } ] },
    { id: 802, name: 'AOC 24G2 24" 1080p 144Hz', vendors: [ { name: 'Vedant', price: 14990, url: 'https://vedantcomputers.com', stock: true } ] },
    { id: 803, name: 'ASUS TUF VG27AQ 27" 1440p 165Hz', vendors: [ { name: 'PrimeABGB', price: 29990, url: 'https://primeabgb.com', stock: true } ] },
    { id: 804, name: 'Dell S2721DGF 27" 1440p 165Hz', vendors: [ { name: 'Dell', price: 32990, url: 'https://dell.com', stock: true } ] },
    { id: 805, name: 'Gigabyte G34WQC 34" Ultrawide 144Hz', vendors: [ { name: 'Amazon', price: 38990, url: 'https://amazon.in', stock: true } ] }
  ]
}
